### ISSUE TITLE
IntelliJ throws an exception about Dagger plugin

### ISSUE THREAD

**Issue by adi-dhulipala** [square/dagger-intellij-plugin#32]
I'm running into a non-user-experience-breaking list of exceptions with the dagger plugin.
It should be noted that I was able to see the little "🗡" icons (and also the different orientation variations of it) in the gutter and was able to navigate to the beans.

However, I believe this error message may be useful to the project.

System Info:
IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 16, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

Stacktrace:
```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 13,4,Idea Thread Group] 1468698127
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2018.1.4#IU-181.5087.20 IDEA, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b39,6,Idea Thread Group] 1973847948
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:371)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:196)
	at com.intellij.psi.impl.source.PsiFileImpl.getContainingDirectory(PsiFileImpl.java:466)
	at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:453)
	at com.intellij.psi.impl.source.PsiFileImpl.getParent(PsiFileImpl.java:67)
	at com.squareup.ideaplugin.dagger.PsiConsultantImpl.findField(PsiConsultantImpl.java:123)
	at com.squareup.ideaplugin.dagger.Decider$ProvidesMethodDecider.shouldShow(Decider.java:38)
	at com.squareup.ideaplugin.dagger.ShowUsagesAction$10.process(ShowUsagesAction.java:403)
	at com.squareup.ideaplugin.dagger.ShowUsagesAction$10.process(ShowUsagesAction.java:391)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$null$6(FindUsagesManager.java:359)
	at com.intellij.util.CommonProcessors$UniqueProcessor.process(CommonProcessors.java:122)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processTextOccurrences$25(PsiSearchHelperImpl.java:1013)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processUsagesInNonJavaFiles$12(PsiSearchHelperImpl.java:520)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:263)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processUsagesInNonJavaFiles(PsiSearchHelperImpl.java:515)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processTextOccurrences(PsiSearchHelperImpl.java:1010)
	at com.intellij.find.findUsages.FindUsagesHelper.processUsagesInText(FindUsagesHelper.java:62)
	at com.intellij.find.findUsages.JavaFindUsagesHelper.processElementUsages(JavaFindUsagesHelper.java:208)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.processElementUsages(JavaFindUsagesHandler.java:246)
	at com.intellij.find.findUsages.FindUsagesManager.lambda$createUsageSearcher$9(FindUsagesManager.java:370)
	at com.intellij.find.findUsages.FindUsagesManager$1.run(FindUsagesManager.java:294)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by flylo** [comment]
I'm getting this as well.
